name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  my-job:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      # ...
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install -g surge
      - run: bun install
      - run: bun run build
      - name: Configure Surge
        run: |
          echo "string.osad.net" > ./dist/CNAME
          cp ./dist/index.html ./dist/200.html

      - name: Deploy to Surge
        run: surge ./dist --token ${{ secrets.SURGE_TOKEN }} --domain string.osad.net